### ISSUE TITLE
TODO refactor branch

### ISSUE THREAD

**Issue by Trufi** [Trufi/TrufiGCD#9]
- [x] В правилах выбирать не профиль, а view
- [x] Добавить во вкладке view возможность создания/удаления/переименования view
- [ ] Брать нужный view из profileSwitcher
- [x] Заиспользовать profile.uuid в свитчере, а не profile.name
